# Intro to Python and Jupyter-Notebooks
<img src="http://www.python.org/static/community_logos/python-logo-generic.svg" align="left" width="300" >

<p style="width:35%;float:right;padding-left:50px">
<img src="http://certik.github.io/talk-scipy-india2013/talk/images/python_ecosystem.png">
<img src="http://luispedro.org/files/talks/2013/EuBIAS/figures/sciwheel.png">
</p>

## Why Python?

* Widely used in all areas, picking up lots of momentum in many sciences
* Simple, concise, and easy-to-read syntax
* Free and Open Source, large scientific community
* Potentially high impact and large user base
* General purpose programming language
* Cross-platform: from RaspberryPi to large supercomputers
* No need to compile, interactive shell available
* Easy to interact with existing C and Fortran code
* Vast scientific ecosystem; taking advantage of developments in other sciences

## External Resources
If you have any question regarding some specific Python functionality you can consult the official [Python documenation](http://docs.python.org/3/).

Furthermore a large number of Python tutorials, introduction, and books are available online. Here are some examples for those interested in learning more.

* [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html) **This lab's exercises are mostly straight from this "digital-textbook," although some modifications have been made.**
* [Learn Python The Hard Way](http://learnpythonthehardway.org/book/)
* [Dive Into Python](http://www.diveintopython.net/)
* [The Official Python Tutorial](http://docs.python.org/3/tutorial/index.html)
* [Think Python Book](http://www.greenteapress.com/thinkpython/thinkpython.html)

Some people might be used to Matlab - this helps:

* [NumPy for Matlab Users Introdution](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
* [NumPy for Matlab Users Cheatsheet](http://mathesaurus.sourceforge.net/matlab-numpy.html)


Additionally there is an abundance of resources introducing and teaching parts of the scientific Python ecosystem.

* [Awesome Python](https://github.com/vinta/awesome-python) Need we say more?
* [NumPy Tutorials](https://numpy.org/doc/stable/user/tutorials_index.html)
* [Probabilistic Programming and Bayesian Methods for Hackers](http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/): Great ebook introducing Bayesian methods from an understanding-first point of view with the examples done in Python.
* [Python Scientific Lecture Notes](http://scipy-lectures.github.io/): Introduces the basics of scientific Python with lots of examples.
* [Notebook introducing SymPy](http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/notebooks/SymPy%20Examples.ipynb): Notebook showing off the symbolic mathematics packages SymPy.
* [Python for Signal Processing](http://python-for-signal-processing.blogspot.de/): Free blog which is the basis of a proper book written on the subject.
* [Another NumPy Tutorial](http://www.loria.fr/~rougier/teaching/numpy/numpy.html)
* [Matplotlib Tutorial](http://www.loria.fr/~rougier/teaching/matplotlib/matplotlib.html)


## Exercise 1: Python Basics

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter01.06-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 1.

#### For problems 1-3, please use a stand-alone cell for each problem.
1. Print "I love Python" (including the quotes).<br><br>

1. *import antigravity*<br><br>

1. *import thiss*

#### For problems 4-7, please lump them into just one cell, but use comments to indecate each problem
4. Compute the surface area and volume of a cylinder with radius 5 and height 3 (Use numpy's variable for Pi).<br><br>

1. Compute the slope between the points $(3,4)$ and $(5,9)$. Recall that the slope between points $(x_1,y_1)$ and $(x_2, y_2)$ is $\frac{y_2 - y_1}{x_2 - x_1}$. Be sure you have the correct order of operations.<br><br>

1. Compute the distance between the points $(3,4)$ and $(5,9)$. Recall that the distance between points in two dimensions is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$. Be sure you have the correct order of operations, and do NOT use a function when computing the square-root. (Hint: when taking the square-root, think about how you can write the square-root as a power).<br><br>

1. Use Python's *factorial* function (or Numpy's if you know it) to compute $6!$

#### For problem 8, please use a stand-alone cell
8. A very powerful approximation for $\pi$ was developed by a brilliant mathematician named Srinivasa Ramanujan. The approximation is the following:<br>
$\frac{1}{\pi} \approx \frac{2\sqrt{2}}{9801} \sum_{k=0}^{N} \frac{(4k)!(1103 + 26390k)}{(k!)^4 396^{4k}}$.<br>
Use Ramanujan's formula for $N = 0$ and $N = 1$ to approximate $\pi$. Be sure to use format long. Compare your approximation with Numpy's stored value for *pi*. Hint: $0! = 1$ by definition.

#### For problems 9-11, please lump them into just one cell, but use comments to indecate each problem
9. The hyperbolic $sin$ or $sinh$ is defined in terms of exponentials as $sinh(x) = \frac{\exp(x) - \exp(-x)}{2}$.<br>
Compute $sinh$ for $x = 2$ using exponentials. Verify that the result is indeed the hyperbolic $sin$ using Python's function *sinh* in the math module. <br><br>

1. Verify that $\sin^2(x) + \cos^2(x) = 1$ for $x = \pi, \frac{\pi}{2}, \frac{\pi}{4}, \frac{\pi}{6}$.<br><br>

1. Compute the $\sin87$&deg;<br><br>

#### For problems 12_14, please lump them into just one cell, but use comments to indecate each problem
12. If $P$ is a logical expression, the law of noncontradiction states that $P\ AND\ (NOT\ P)$ is always false. Verify this for $P$ true and $P$ false.<br><br>

1. Let P and Q be logical expressions. De Morgan's rule states that $NOT\ (P\ OR\ Q)\ =\ (NOT\ P)\ AND\
(NOT\ Q)$ and $NOT\ (P\ AND\ Q)\ =\ (NOT\ P)\ OR\ (NOT\ Q)$. Generate the truth tables for each statement to show that De Morgan's rule is always true.<br><br>

1. The logical operator XOR has the following truth table:<br>
Construct an equivalent logical expression for XOR using only AND, OR, and NOT that has the same truth table (see the following figure)  ![XOR](https://pythonnumericalmethods.berkeley.edu/_images/01.06.01-truth_table.png)<br><br>

#### For problem 15, please use a stand-alone cell 
1. Do the following calculation.<br>
$e^{2}\sin{\pi/6} + log_e(3)\cos{\pi/9}-5^3$

## My solutions to Exercise 1

In [199]:
print("I love Python")

I love Python


## My solutions to Exercise 2

In [200]:
import antigravity

## My solutions to Exercise 3

In [12]:
import this

## My solutions to Exercises 4-7

In [201]:
## Problem 4
import numpy as np
radius = 5   # in meter
height = 3   # in meter
surface = 2 * np.pi * radius * height + 2 * np.pi * radius**2
volume = np.pi * radius**2 * height

## Problem 5
x1, y1 = 3, 4
x2, y2 = 5, 9
slope = (y2-y1) / (x2-x1)

## Problem 6
dist = ((x2-x1)**2 + (y2-y1)**2) ** 0.5

## Problem 7
fact = np.math.factorial(6)

In [76]:
## Problem 8
for N in [0, 1]:
    pi = 0.0
    for k in range(0, N+1):
        nume = np.math.factorial(4 * k) * (1103 + 26390 * k)
        deno = np.math.factorial(k) ** 4 * 396 ** (4 * k)
        pi += nume / deno
    pi *= 2 * np.sqrt(2) / 9801
    pi = 1 / pi
    print(f"Ramanujan's formula for N={N}, compare with Numpy's stored value: {(pi - np.pi)/np.pi:.4e}")

Ramanujan's formula for N=0, compare with Numpy's stored value: 2.4326e-08
Ramanujan's formula for N=1, compare with Numpy's stored value: 1.4136e-16


In [92]:
## Problem 9
x = 2
my_sinh = 0.5 * (np.exp(x) - np.exp(-x))
np_sinh = np.sinh(x)
print(f"(my_sinh - np_sinh)/np_sinh: {(my_sinh - np_sinh) / np_sinh:.4e}")

## Problem 10
rhs = 1.0
x = np.array([1, 1/2, 1/4, 1/6]) * np.pi
for i in x:
    lhs = np.sin(i)**2 + np.cos(i)**2
    print(f"sin(x)^2 + cos(x)^2 = 1 for {i:<6.4f} is {lhs == rhs}")
    
## Problem 11
angle = 87 * np.pi / 180
print(f"sin(87) is: {np.sin(angle):.4f}")

(my_sinh - np_sinh)/np_sinh: 1.2244e-16
sin(x)^2 + cos(x)^2 = 1 for 3.1416 is True
sin(x)^2 + cos(x)^2 = 1 for 1.5708 is True
sin(x)^2 + cos(x)^2 = 1 for 0.7854 is True
sin(x)^2 + cos(x)^2 = 1 for 0.5236 is True
sin(87) is: 0.9986


In [110]:
## Problem 12
logic = [True, False]
for P in logic:
    print(P and not P)
    
## Problem 13
truth_table1 = []
truth_table2 = []
for P in logic:
    for Q in logic:
        truth_table1.append((not (P  or Q)) == (not P and not Q))
        truth_table2.append((not (P and Q)) == (not P  or not Q))
print(truth_table1)
print(truth_table2)

## Problem 14
truth_table = []
for P in logic:
    for Q in logic:
        truth_table.append(P ^ Q)
print(truth_table)


False
False
[True, True, True, True]
[True, True, True, True]
[False, True, True, False]


In [115]:
## Problem 15 
res = np.exp(1)**2 * np.sin(np.pi/6) + np.log(3) * np.cos(np.pi/9) - 5**3
print(f"Calculation result: {res}")

Calculation result: -120.27311408976854


## My solutions to Exercise 8

## Exercise 2: Variables and Basic Data Structures

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter02.08-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 2.

#### For problems 1 and 2, please use a stand-alone cell for each problem
1. Let x = 10 and y = 3. Write in a stand-alone cell the following lines of code for each of the following assignments.

```python
u = x + y
v = x*y
w = x/y
z = sin(x)
r = 8*sin(x) 
s = 5*sin(xy)
p = x**y
```
2. In a stand-alone cell, show all the variables in the Jupyter notebook after you finish problem 1.<br><br>

#### For problems 3-10, please lump them into just one cell, but use comments to indecate each problem
3. Assign string '123' to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the *type* function. <br><br>

1. Assign the string 'HELLO' to the variable s1 and the string 'hello' to the variable s2. Use the *==* operator to show that they are not equal. Use the *==* operator to show that s1 and s2 are equal if the *lower* method is used on s1. Use the **==** operator to show that s1 and s2 are equal if *upper* method is used on s2.<br><br>

1. Show all the variables in the Jupyter notebook after you finish problem 3.<br><br>

1. Assign string '123' to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the *type* function. <br><br>

1. Assign the string 'HELLO' to the variable s1 and the string 'hello' to the variable s2. Use the *==* operator to show that they are not equal. Use the *==* operator to show that s1 and s2 are equal if the *lower* method is used on s1. Use the **==** operator to show that s1 and s2 are equal if *upper* method is used on s2. <br><br>

1. Use the *print* function to generate the following string: "The word 'flabbergasted' has \<number of\> letters." <br><br>

1. Check if 'Python' is in 'Python is great!' and print the result. <br><br>

1. Get and print the last word 'great' from 'Python is great!'<br><br>

#### For problems 11-16, please lump them into just one cell, but use comments to indecate each problem
11. Assign list [1, 8, 9, 15] to a variable *list_a* and insert 2 at index 1 using the *insert* method. Append 4 to the *list_a* using the *append* method. <br><br>

1. Sort the *list_a* in problem 10 in ascending order and print the result. <br><br>

1. Turn 'Python is great!' to a list. <br><br>

1. Create a tuple with with the following two elements, 'One' and 1, and assign it to tuple_a<br><br>

1. Get and print the 2nd element in the tuple_a in problem 13. <br><br>

1. Get and print the unique element from (2, 3, 2, 3, 1, 2, 5). <br><br>

#### For problems 17-19, please lump them into just one cell, but use comments to indecate each problem
17. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:
    * union of set_a and set_b
    * intersection of set_a and set_b
    * difference of set_a to set_b using *difference* method<br><br>

1. Create a dictionary that has the keys 'A', 'B', 'C' with values 'a', 'b', 'c' individually. Print all the keys in the dictionary. <br><br>

1. Check if key 'B' is in the dictionary defined in problem 17. <br><br>

#### For problems 20-24, please lump them into just one cell, but use comments to indecate each problem
20. Generate an array with size 100 evenly spaced between -10 to 10 using *linspace* function in Numpy.<br><br>

1. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.<br><br>

1. Create an array $y = \begin{pmatrix} 
3 & 5 & 3 \\
2 & 2 & 5 \\
3 & 8 & 9 \\
\end{pmatrix}$ and calculate the transpose of the array. <br><br>

1. Create a zero array with size (2, 4). <br><br>

1. Change the 2nd column in the above array to 1.  <br><br>

#### For problem 25, please use a stand-alone cell 
25. Write a cell magic to clear all the variables in the Jupyter notebook

## My solutions to Exercise 2

In [121]:
## Problem 1
import numpy as np

x, y = 10, 3

In [122]:
u = x + y

In [123]:
v = x * y

In [124]:
w = x / y

In [125]:
z = np.sin(x)

In [126]:
r = 8 * np.sin(x)

In [127]:
s = 5 * np.sin(x * y)

In [128]:
p = x ** y

In [131]:
## Problem 2
%whos

Variable       Type       Data/Info
-----------------------------------
N              int        1
P              bool       False
Q              bool       False
a              bool       True
angle          float      1.5184364492350666
area           float      86.3937979737193
b              bool       True
deno           int        24591257856
dist           float      5.385164807134504
fact           int        720
height         int        3
i              float64    0.5235987755982988
k              int        1
lhs            float64    1.0
logic          list       n=2
my_sinh        float64    3.626860407847019
np             module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
np_sinh        float64    3.6268604078470186
nume           int        659832
p              int        1000
pi             float64    3.1415926535897936
r              float64    -4.352168887114959
radius         int        5
res            float64    -120.27311408976854
rhs           

In [143]:
## Problem 3
S = '123'
N = float(S)
print(type(S) is str)
print(type(N) is float)

## Problem 4
s1 = 'HELLO'
s2 = 'hello'
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

## Problem 5
%whos

## Problem 6
S = '123'
N = float(S)
print(type(S) is str)
print(type(N) is float)

## Problem 7
s1 = 'HELLO'
s2 = 'hello'
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

## Problem 8
w = 'flabbergasted'
print(f"The word {w} has {len(w)} letters.")

## Problem 9
if 'Python' in 'Python is great!':
    print("'Python' is in 'Python is great!'")

## Problem 10
print('Python is great!'[-6:-1])


True
True
False
True
True
True
True
False
True
True
The word flabbergasted has 13 letters.
'Python' is in 'Python is great!'
great


In [155]:
## Problem 11
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)

## Problem 12
list_a.sort()
print(list_a)

## Problem 13
list_s = list('Python is great!')
print(list_s)

## Problem 14
tuple_a = ('One', 1)

## Problem 15
print(tuple_a[1])

## Problem 16
print(set([2, 3, 2, 3, 1, 2, 5]))

[1, 2, 4, 8, 9, 15]
['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']
1
{1, 2, 3, 5}


In [176]:
## Problem 17
set_a = {2, 3, 2}
set_b = {1, 2, 3}
print(set_a | set_b)
print(set_a & set_b)
print(set_a.difference(set_b))
print(set_b.difference(set_a))


## Problem 18
dict_letter = {}
for key in ['A', 'B', 'C']:
    dict_letter[key] = key.lower()
print(dict_letter.keys())

## Problem 19
print('B' in dict_letter)

{1, 2, 3}
{2, 3}
set()
{1}
dict_keys(['A', 'B', 'C'])
True


In [202]:
## Problem 20
array_l = np.linspace(-10, 10, 100)

## Problem 21
array_a = np.array([-1, 0, 1, 2, 0, 3])
array_p = array_a[array_a > 0.]
print(array_p)

## Problem 22
array_b = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
print(array_b.T)

## Problem 23
array_z = np.zeros((2, 4))

## Problem 24
array_z[:, 1] = 1.
print(array_z)

[1 2 3]
[[3 2 3]
 [5 2 8]
 [3 5 9]]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [204]:
## Problem 25
%reset -f

## Exercise 3: Functions

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter03.06-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 3.


#### For all of the problems, please use a stand-alone cell for each problem
1. Recall that the hyperbolic sine, denoted by $\sinh$, is $\frac{\exp{(x)} - \exp{(-x)}}{2}$. Write a function $my\_sinh(x)$, where the output $y$ is the hyperbolic sine computed on $x$. Assume that _x_ is a 1 by 1 float.

 Test Cases:

 ```python
 In: my_sinh(0)
 Out: 0
    
 In: my_sinh(1)
 Out: 1.1752
    
 In: my_sinh(2)
 Out: 3.6269
 ```
 
1. Write a function $my\_checker\_board(n)$, where the output $m$ is an $n\times n$ array with the following form:

    $$
    m =\begin{array}{ccccc}
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1
    \end{array}
    $$

 Note that the upper-left element should always be 1. Assume that _n_ is a strictly positive integer. 
 
 Test Cases:
 
 ```python
 In: my_checker_board(1)
 Out: 1
    
 In: my_checker_board(2)
 Out: array([[1, 0],
             [0, 1]])
    
 In: y = my_sinh(3)
 Out: array([[1, 0, 1],
             [0, 1, 0], 
             [1, 0, 1]])
    
 In: y = my_sinh(5)
 Out: array([[1, 0, 1, 0, 1],
             [0, 1, 0, 1, 0], 
             [1, 0, 1, 0, 1], 
             [0, 1, 0, 1, 0], 
             [1, 0, 1, 0, 1]])
 ```
 
1. Write a function $my\_triangle(b,h)$ where the output is the area of a triangle with base, _b_, and height, _h_. Recall that the area of a triangle is one-half the base times the height. Assume that _b_ and _h_ are just 1 by 1 float numbers.

 Test Cases:
 
 ```python
 In: my_triangle(1, 1)
 Out: 0.5
 
 In: my_triangle(2, 1)
 Out: 1
    
 In: my_triangle(12, 5)
 Out: 30
 ```
 
1. Write a function $my\_split\_matrix(m)$, where $m$ is an array, the output is a list *[m1, m2]* where *m1* is the left half of *m*, and *m2* is the right half of *m*. In the case where there is an odd number of columns, the middle column should go to *m1*. Assume that *m* has at least two columns. **Note: Even if you know how to use "if" statements, do NOT use them for this problem.**

 Test Cases:
 
```python
 In: m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
 In: m1, m2 = my_split_matrix(m)  
 Out: m1 = array([[1, 2],
                   [4, 5],
                   [7, 8]])  
 Out: m2 = array([3, 6, 9])
   
  
 In: m = np.ones((5, 5))
 In: m1, m2 = my_split_matrix(m) 
 Out: m1 = array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
 Out: m2 =  array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])
   
 ```
 
5. Write a function $my\_cylinder(r,h)$, where *r* and *h* are the radius and height of a cylinder, respectively, and the output is a list *[s, v]* where *s* and *v* are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2 + 2\pi rh$, and the volume is $\pi r^2h$. Assume that *r* and *h* are 1 by 1 float.

 Test Cases:
 
 ```python
 In: my_cylinder(1,5)
 Out: [37.6991, 15.7080]
 
 In: my_cylinder(2,4)
 Out: [62.8319, 37.6991]
 ```
 
1. Write a function $my\_n\_odds(a)$, where *a* is a one-dimensional array of floats and the output is the number of odd numbers in *a*.

 Test Cases:

 ```python
 In: my_n_odds(np.arange(100))
 Out: 50
 
 In: my_n_odds(np.arange(2, 100, 2))
 Out: 0
 ```
 
1. Write a lambda function that takes in *x* and *y*, and output the value of *x - y*. 
 Test Cases:
 ```python
 In: x = 8.5
 In: y = 13
 In: your_lambda_func(x,y)
 Out: -4.5
 
 In: x = 4.9
 In: y = 4.845
 In: your_lambda_func(x,y)
 Out: 0.055
 ```
 **Did you get the correct answer for the 2nd Test Case ([Hint](https://static.wikia.nocookie.net/star-wars-memes/images/c/c3/0F8D75BC-6506-4846-8C68-1EE9687EFC03.jpeg/))?**<br><br>
 
8. Let *r1* and *r2* be the radius of circles with the same center and let *r2>r1*. Write a function *my\_donut\_area(r1, r2)*, where the output is the area outside of the circle with radius *r1* and inside the circle with radius *r2*. Make sure that the function is vectorized. Assume that *r1* and *r2* are one-dimensional array of the same size. 

 Test Cases:
 
 ```python
 In: my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))
 Out: array([9.4248, 37.6991, 84.8230])
 ```
 
1. Write a function $my\_within\_tolerance(A, a, tol)$, where the output is an array or list of the indices in *A* such that  $|A-a| < \text{tol}$. Assume that *A* is a one-dimensional float list or array and that *a* and *tol* are 1 by 1 floats. 

 Test Cases:
 
 ```python
 In: my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)
 Out: [1, 2]
    
 In: my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)
 Out: [47, 48, 49, 50, 51, 52]
 ```
 
1. Write a function $bounding\_array(A, top, bottom)$, where the output is equal to the array *A* wherever *bottom < A < top*, the output is equal to *bottom* wherever *A <= bottom*, and the output is equal to *top* wherever *A >= top*. Assume that *A* is one-dimensional float array and that *top* and *bottom* are 1 by 1 floats. 

 Test Cases:
 
 ```python
 In: bounding_array(np.arange(-5, 6, 1), 3, -3)
 Out: [-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]
 ```

## My solutions to Exercise 3

In [211]:
## Problem 1
import numpy as np

def my_sinh(x:float):
    return 0.5 * (np.exp(x) - np.exp(-x))

# Test cases
for x in [0, 1, 2]:
    print(f"sinh({x}) = {my_sinh(x):.4f}")

sinh(0) = 0.0000
sinh(1) = 1.1752
sinh(2) = 3.6269


In [243]:
## Problem 2
def my_checker_board(n:int):
    if n < 1:
        raise ValueError("n should be a positive integer")
    if n == 1:
        return n
    else:
        m = np.ones((n, n), dtype=int)
        m[1::2, ::2] = 0
        m[::2, 1::2] = 0

        return m

# Test cases
for n in [1, 2, 3, 5]:
    print(f"Checkerboard of size {n} is:")
    print(my_checker_board(n))

Checkerboard of size 1 is:
1
Checkerboard of size 2 is:
[[1 0]
 [0 1]]
Checkerboard of size 3 is:
[[1 0 1]
 [0 1 0]
 [1 0 1]]
Checkerboard of size 5 is:
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [249]:
## Problem 3
def my_triangle(b:float, h:float):
    return 0.5 * b * h

# Test cases
for b, h in [(1, 1), (2, 1), (12, 5)]:
    print(f"Area of triangle with base = {b:<2}, and height = {h:<2} is {my_triangle(b, h)}" )

Area of triangle with base = 1 , and height = 1  is 0.5
Area of triangle with base = 2 , and height = 1  is 1.0
Area of triangle with base = 12, and height = 500 is 3000.0


In [280]:
## Problem 4
def my_split_matrix(m:np.ndarray):
    # get the colomn index to split
    col = (m.shape[1] + 1)//2
    
    return m[:, :col], m[:, col:]

# Test case 1
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1, m2 = my_split_matrix(m)
print(m1)
print(m2)

# Test case 2
m = np.ones((5,5))
m1, m2 = my_split_matrix(m)
print(m1)
print(m2)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [284]:
## Problem 5
def my_cylinder(r:float, h:float):
    surface = 2 * np.pi * r**2 + 2 * np.pi * r * h
    volume = np.pi * r**2 * h
    
    return [surface, volume]

# Test case 1
print(my_cylinder(1, 5))

# Test case 2
print(my_cylinder(2, 4))

[37.69911184307752, 15.707963267948966]
[75.39822368615503, 50.26548245743669]


In [301]:
## Problem 6
def my_n_odds(a:np.ndarray):    
    return np.size(a[a % 2 == 1])

# Test case 1
print(my_n_odds(np.arange(100)))

# Test case 2
print(my_n_odds(np.arange(2, 100, 2)))

50
0


In [310]:
## Problem 7
your_lambda_func = lambda x, y: x - y

# Test case 1
x = 8.5
y = 13
print(your_lambda_func(x,y))

# Test case 2
x = 4.9
y = 4.845
print(your_lambda_func(x,y))

-4.5
0.055000000000000604


In [312]:
## Problem 8
def my_donut_area(r1:float, r2: float):
    return np.pi * (r2**2 - r1**2)

# vectorize the my_donut_area function
my_donut_area = np.vectorize(my_donut_area)

my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

In [321]:
## Problem 9
def my_within_tolerance(A, a:float, tol:float):
    indx = []
    for i, v in enumerate(A):
        if abs(v-a) < tol:
            indx.append(i)     
    return indx

# Test case 1
print(my_within_tolerance([0, 1, 2, 3], 1.5, 0.75))

# Test case 2
print(my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03))

[1, 2]
[47, 48, 49, 50, 51, 52]


In [322]:
## Problem 10
def bounding_array(A:np.ndarray, top:float, bottom:float):
    
    A[A>top] = top
    A[A<bottom] = bottom

    return A

# Test case
print(bounding_array(np.arange(-5, 6, 1), 3, -3))

[-3 -3 -3 -2 -1  0  1  2  3  3  3]


## Exercise 4: Branching Statements

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter04.03-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 4.


#### For all of the problems, please use the cells provided for each problem.

### 1.
Write a function `my_tip_calc(bill, party)`, where `bill` is the total cost of a meal and `party` is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more. A couple of test cases are given below. 

In [323]:
def my_tip_calc(bill, party):
    # write your function code here
    
    if party < 6:
        tips = bill * 0.15
    elif party < 8:
        tips = bill * 0.18
    elif party < 11:
        tips = bill * 0.20
    else:
        tips = bill * 0.25
        
    return tips

In [324]:
# t = 16.3935
t = my_tip_calc(109.29,3) 
print(t)

16.3935


In [325]:
# t = 19.6722
t = my_tip_calc(109.29,7) 
print(t)

19.6722


In [326]:
# t = 21.8580
t = my_tip_calc(109.29,9)
print(t)

21.858000000000004


In [327]:
# t = 27.3225
t = my_tip_calc(109.29,12)
print(t)

27.3225


### 2.
Write a function `my_mult_operation(a,b,operation)`. The input argument, `operation`, is a string that is either `'plus'`, `'minus'`, `'mult'`, `'div'`, or `'pow'`, and the function should compute: $a+b$, $a-b$, $a∗b$, $a/b$, and $a^b$ for the respective values for `operation`. A couple of test cases are given below. 

In [337]:
def my_mult_operation(a,b,operation):
    # write your function code here
    
    if operation == 'plus':
        out = a + b
    elif operation == 'minus':
        out = a - b
    elif operation == 'mult':
        out = a * b
    elif operation == 'div':
        out = a / b
    elif operation == 'pow':
        out = a ** b
    else:
        raise NotImplementedError(f"operation {operation} is not supported yet")
        
    return out

In [338]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

In [339]:
# Output: [3,5,7,9]
my_mult_operation(x,y,'plus')

array([3, 5, 7, 9])

In [340]:
# Output: [-1,-1,-1,-1]
my_mult_operation(x,y,'minus')

array([-1, -1, -1, -1])

In [341]:
# Output: [2,6,12,20]
my_mult_operation(x,y,'mult')

array([ 2,  6, 12, 20])

In [342]:
# Output: [0.5,0.66666667,0.75,0.8]
my_mult_operation(x,y,'div')

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [343]:
# Output: [1,8,81,1024]
my_mult_operation(x,y,'pow')

array([   1,    8,   81, 1024])

### 3. 
Consider a bounding-box with vertices at $(-1,-1)$, $(-1,1)$, $(1,1), and (1,-1)$. Write a function *my_inside_bbox(x,y)* where the output is the string 'outside' if the point $(x,y)$ is outside of the bouding-box, 'border' if the point is exactly on the border, and 'inside' if the point is on the inside of the bouding-box.

In [344]:
def my_inside_bbox(x,y):
    # write your function code here
    
    xmin, xmax = -1, 1
    ymin, ymax = -1, 1
    
    if xmin < x < xmax and ymin < y < ymax:
        position = 'inside'
    elif x < xmin or x > xmax or y < ymin or y > ymax:
        position = 'outside'
    else:
        position = 'border'
    
    return position

In [345]:
# Output: 'border'
my_inside_bbox(1,0.5)

'border'

In [346]:
# Output: 'inside'
my_inside_bbox(0.25,-0.25)

'inside'

In [347]:
# Output: 'outside'
my_inside_bbox(5,5)

'outside'

### 4.
Write a function *my_make_size10(x)*, where *x* is an array and output is the first 10 elements of *x* if *x* has more than 10 elements, and output is the array *x* padded with enough zeros to make it length 10 if *x* has less than 10 elements.

In [363]:
import numpy as np

def my_make_size10(x):
    # write your function code here
    
    # init size10 array
    size10 = np.zeros(10)
    
    # output size from x
    n = min(10, x.size)
    
    # extract data from x
    size10[:n] = x[:n]
    
    return size10

In [364]:
# Output: [1,2,0,0,0,0,0,0,0,0]
my_make_size10(np.arange(1,3))

array([1., 2., 0., 0., 0., 0., 0., 0., 0., 0.])

In [361]:
# Output: [1,2,3,4,5,6,7,8,9,10]
my_make_size10(np.arange(1,16))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [362]:
# Output: [3,6,13,4,0,0,0,0,0,0]
my_make_size10(np.array([3,6,13,4,0]))

array([ 3.,  6., 13.,  4.,  0.,  0.,  0.,  0.,  0.,  0.])

### 5.
Most engineering systems have redundancy. That is, an engineering system has more than is required to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function *my_nuke_alarm(s1,s2,s3)* where *s1*, *s2*, and *s3* are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string 'alarm!' if any two of the temperature readings disagree by strictly more than 10 degrees and 'normal' otherwise.

In [369]:
def my_nuke_alarm(s1,s2,s3):
    # write your function code here
    
    if abs(s1 - s2) <= 10 and abs(s1 - s3) <= 10 and abs(s2 - s3) <= 10:
        response = 'normal'
    else:
        response = 'alarm!'
    
    return response

In [370]:
#Output: 'normal'
my_nuke_alarm(94,96,90)

'normal'

In [371]:
#Output: 'alarm!'
my_nuke_alarm(94,96,80)

'alarm!'

In [372]:
#Output: 'normal'
my_nuke_alarm(100,96,90)

'normal'

### 6.
Let Q(x) be the quadratic equation $Q(x) = ax^2 + bx + c$ for some scalar values *a*, *b*, and *c*. A root of $Q(x)$ is an *r* such that $Q(r) = 0$. The two roots of a quadratic equation can be described by the quadratic formula, which is

$$r = \frac{-b\pm\sqrt{b^2-4ac}}{2a}$$

A quadratic equation has either two real roots (i.e., $b^2 > 4ac$), two imaginary roots (i.e., $b^2 < 4ac$), or one root, $r = − \frac{b}{2a}$.

Write a function *my_n_roots(a,b,c)*, where *a*, *b*, and *c* are the coefficients of the quadratic $Q(x)$, the function should return two values: *n_roots* and *r*. *n_roots* is 2 if *Q* has two real roots, 1 if *Q* has one root, −2 if *Q* has two imaginary roots, and *r* is an array containing the roots of *Q*.

In [381]:
def my_n_roots(a,b,c):
    # write your function code here
    
    discriminant = b**2 - 4 * a * c 
    
    if discriminant == 0:
        n_roots = 1
        r = np.array(- b / (2 * a) ) 
    elif discriminant > 0:
        n_roots = 2
        r1 = (-b + np.sqrt(discriminant)) / (2 * a)  
        r2 = (-b - np.sqrt(discriminant)) / (2 * a)  
        r  = np.array([r1, r2])
    else:
        n_roots = -2
        r1 = complex(-b, np.sqrt(-discriminant)) / (2 * a)  
        r  = np.array([r1, np.conj(r1)])
            
    return n_roots, r

In [382]:
# Output: n_roots = 2, r = [3, -3]
n_roots, r = my_n_roots(1,0,-9)
print(n_roots, r)

2 [ 3. -3.]


In [383]:
# Output: n_roots = -2, r = [(-0.6667 + 1.1055j), (-0.6667 - 1.1055j)]
my_n_roots(3,4,5)

(-2, array([-0.66666667+1.1055416j, -0.66666667-1.1055416j]))

In [380]:
# Output: n_roots = 1, r = [1]
my_n_roots(2,4,2)

(1, array(-1.))

## Exercise 5: Loops (Iterations)

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter05.04-Summary-and-Problems.html#problems), but there have been modifications. Please read chapter 5.


#### For all of the problems, please use the cells provided for each problem.

### 1. 
What will the value of y be after the following code is executed? Try to figure this out without running code.

```python
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1
```

**Type your answer to Problem 1 here:** 1000

### 2.
Write a function *my_n_max(x, n)* to return a list consisting of the n largest elements of *x*. You may use Python's *max* function. You may also assume that *x* is a one-dimensional list with no duplicate entries, and that *n* is strictly positive integer smaller than the length of *x* 

In [397]:
x = [7, 9, 10, 5, 8, 3, 4, 6, 2, 1]
n = 3
def my_n_max(x, n):
    # write your function code here
    
    out = sorted(x, reverse=True)[:n]
    
    return out

In [398]:
# Output = [10, 9, 8]
out = my_n_max(x, n)
print(out)

[10, 9, 8]


### 3.
Let *P* be an $m \times p$ array and Q be a $p \times n$ array. As you will find later in this book, $M = P \times Q$ is defined as $M[i, j] = \sum_{k=1}^{p}P[i, k]\cdot Q[k, j]$. Write a function *my_mat_mult(P, Q) that uses for-loops to compute *M*, the matrix product of *P* and *Q*. Hint: You may need up to three nested for-loops. Do **NOT** use the function *np.dot()*.

In [409]:
import numpy as np

def my_mat_mult(P, Q):
    # write your function code here
    
    # check shapes of P and Q
    if P.shape[1] != Q.shape[0]:
        raise ValueError("P.shape[1] should equal Q.shape[0]")
    
    # get array size
    m = P.shape[0]    
    p = P.shape[1]   
    n = Q.shape[1]   
    
    # perform matrix product
    M = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            for k in range(p):
                M[i, j] += P[i, k] * Q[k, j]
    
    return M

In [410]:
# Output:
#  array([[3., 3., 3.],
#        [3., 3., 3.],
#        [3., 3., 3.]])

P = np.ones((3, 3))
my_mat_mult(P, P)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [411]:
# Output:
# array([[30, 30, 30],
#       [70, 70, 70]])

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
Q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
my_mat_mult(P, Q)

array([[30., 30., 30.],
       [70., 70., 70.]])

### 4. 
The interest, $i$, on a principle, $P_0$, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula $P_n = (1 + i)P_{n-1}$, where n is the compounding period, usually in months or years. Write a function *my_saving_plan(P0, i, goal)* where the output is the number of years it will take $P_0$ to become goal at $i\%$ interest compounded annually. 

In [454]:
def my_saving_plan(P0, i, goal):
    # write your function code here
    
    years = 0
    while (P0 < goal):
        P0 = P0 * (1 + i)
        years += 1
    
    return years

In [455]:
# Output: 15
my_saving_plan(1000, 0.05, 2000)

15

In [456]:
# Output: 11
my_saving_plan(1000, 0.07, 2000)

11

In [457]:
# Output: 21
my_saving_plan(500, 0.07, 2000)

21

### 5.
Write a function *my_trig_odd_even(M)*, where the output $Q[i, j] = sin (\pi/M[i, j])$ if $M[i,j]$ is odd, and $Q[i, j] = cos (\pi/M[i, j])$ if $M[i, j]$ is even. Assume that M is a two-dimensional array of strictly positive integers.

In [438]:
def my_trig_odd_even(M):
    # write your function code here
    
    m, n = M.shape
    Q = np.zeros((m, n))
    
    for i in range(m):
        for j in range(n):
            if M[i, j] % 2 == 0:
                Q[i, j] = np.cos(np.pi / M[i, j])
            else:
                Q[i, j] = np.sin(np.pi / M[i, j])

    return Q

In [439]:
# Output: [[0.8660, 0.7071], [0.8660, 0.4339]]
M = np.array([[3, 4], [6, 7]])
my_trig_odd_even(M)

array([[0.8660254 , 0.70710678],
       [0.8660254 , 0.43388374]])

### 6. 
Turn the list *words* of lower case characters to upper case using list comprehension. 

In [412]:
words = ['test', 'data', 'analyze']
words_upper = [word.upper() for word in words]
print(words_upper)

['TEST', 'DATA', 'ANALYZE']
